### ISSUE TITLE
Zarovnat links div

### ISSUE THREAD

**Issue by globalistas** [globalistas/ceknito#21]
Bez toho, aby to ovplyvnilo front page resp. sub page. Iba v ramci postov.

![image](https://user-images.githubusercontent.com/64347618/89306523-4aedc880-d670-11ea-9bfa-95a349423c8a.png)

**Comment by novotnicek** [comment]
treba myslieť na dedičnosť CSS. jednotlivé príspevky majú svoju classu **"wholepost"**.
https://github.com/globalistas/ceknito/blob/9a9058b28555a90de3868d08bf101ebeef846508/app/html/sub/post.html#L53
vlastnosti ktoré chceš priradiť tým elementom musíš "adresovať" pre:
* .wholepost .postinfo
* .wholepost .comments

napríklad:
```css
.wholepost .postinfo .links a {
  color: #666;
}
```

**Comment by globalistas** [comment]
Closed by https://github.com/globalistas/ceknito/commit/659235766c609df45ac33103f8009de6e8b33a8a
