### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by globalistas** [globalistas/ceknito#5]
Aktualne je scrollbar definovany

`body::-webkit-scrollbar {
   width: 4px;
   background: #800000;
   z-index: -1;
}`

a

`body::-webkit-scrollbar-thumb {
    background: rgb(16, 16, 16);
}`

(to druhe neviem co presne robi)

Ten bar je prilis uzky a v mojom browseri (Vivaldi) skrolovanie cez bar napr. vobec nefunguje, tak asi bude lepsie uplne ten scrollbar vycommentovat, nech tam je proste nativny scrollbar. Ak to nesposobi ine problemy...

**Comment by novotnicek** [comment]
`body::-webkit-scrollbar` je cela plocha scrollbaru a `body::-webkit-scrollbar-thumb` je iba ta cast za ktoru sa da "tahat".
bud to zacommentuj (idealne kvoli mergom s upstream-om) alebo uplne odstran (idealne kvoli cistote kodu). naozaj neviem preco maju niektori devs potrebu rozbijat systemove UI...

**Comment by globalistas** [comment]
closed via https://github.com/globalistas/ceknito/commit/942dbd634830207c368c4e71253fd38e835b05b7
